import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import PromotionalBar from "@/components/navbar/promotionalBar"
// import Header from "@/components/header/Header";
import SearchBar from "@/components/searchBar/SearchBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <PromotionalBar  />
      <SearchBar user={null}/>
        {children}
      </body>
    </html>
  );
}
